# تخصيص مساحة ذاكرة كافية لـ Gradle لتفادي أخطاء OutOfMemory أثناء البناء
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# تفعيل دعم مكتبات AndroidX الحديثة
android.useAndroidX=true

# تمكين التبديل التلقائي للمكتبات القديمة إلى AndroidX
android.enableJetifier=true

# تحسين سرعة البناء المتوازي
org.gradle.parallel=true

# استخدام التخزين المؤقت لمهام البناء لتسريع التجميع
org.gradle.caching=true
